/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import cadastros.CadastroPadrao;
import cadastros.PainelBairros;
import cadastros.PainelClientes;
import cadastros.PainelFuncionarios;
import cadastros.PainelProdutos;
import controller.BairroController;
import controller.ClienteController;
import controller.FuncionarioController;
import controller.ProdutoController;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }
    
    private void atualizarHora() {  
        Timer timer = new Timer(1000, e -> { // Cria um Timer para atualizar a cada segundo
             Date dataHoraAtual = new Date();
        String horaFormatada = new SimpleDateFormat("HH:mm:ss").format(dataHoraAtual);

        // Atualiza o JLabel utilizando SwingUtilities.invokeLater
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                jhora.setText(horaFormatada);
            }
        });
    });
    timer.start(); // Inicia o Timer
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jhora = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        img = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmBairro = new javax.swing.JMenuItem();
        jmCliente = new javax.swing.JMenuItem();
        jmFuncionario = new javax.swing.JMenuItem();
        jmProdutos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 200, 220));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jhora.setText(":");
        jPanel1.add(jhora);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(248, 200, 220));

        jButton1.setBackground(new java.awt.Color(238, 201, 210));
        jButton1.setForeground(new java.awt.Color(255, 20, 147));
        jButton1.setText("Clientes");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jButton1);

        jbSair.setBackground(new java.awt.Color(238, 201, 210));
        jbSair.setForeground(new java.awt.Color(255, 20, 147));
        jbSair.setText("Sair");
        jbSair.setToolTipText("");
        jbSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });
        jPanel4.add(jbSair);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        img.setBackground(new java.awt.Color(51,0,255));

        img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/emoji-joinha.jpeg")));
        img.setLabelFor(img);
        jPanel3.add(img, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(248, 200, 220));

        jMenu1.setText("Cadastros");

        jmBairro.setText("Cadastro de Bairro");
        jmBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBairroActionPerformed(evt);
            }
        });
        jMenu1.add(jmBairro);

        jmCliente.setText("Cadastro de Cliente");
        jmCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jmCliente);

        jmFuncionario.setText("Cadastro de Funcionario");
        jmFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFuncionarioActionPerformed(evt);
            }
        });
        jMenu1.add(jmFuncionario);

        jmProdutos.setText("Cadastro de Produtos");
        jmProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(jmProdutos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Listar");

        jMenuItem5.setText("Bairros");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Clientes");
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ajuda");

        jMenuItem1.setText("Sobre");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBairroActionPerformed
        new CadastroPadrao(this, new PainelBairros(), new BairroController(), true).setVisible(true);
    }//GEN-LAST:event_jmBairroActionPerformed

    private void jmClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmClienteActionPerformed
        new CadastroPadrao(this, new PainelClientes(), new ClienteController(), true).setVisible(true);
    }//GEN-LAST:event_jmClienteActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "se abriu aqui, me deve 10 reais");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbSairActionPerformed

    private void jmFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFuncionarioActionPerformed
       new CadastroPadrao(this, new PainelFuncionarios(), new FuncionarioController(), true).setVisible(true);
    }//GEN-LAST:event_jmFuncionarioActionPerformed

    private void jmProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmProdutosActionPerformed
        new CadastroPadrao(this, new PainelProdutos(), new ProdutoController(), true).setVisible(true);
    }//GEN-LAST:event_jmProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbSair;
    private javax.swing.JLabel jhora;
    private javax.swing.JMenuItem jmBairro;
    private javax.swing.JMenuItem jmCliente;
    private javax.swing.JMenuItem jmFuncionario;
    private javax.swing.JMenuItem jmProdutos;
    // End of variables declaration//GEN-END:variables
}
