package app;

import cadastros.CadastroPadrao;
import cadastros.PainelBairros;
import cadastros.PainelClientes;
import cadastros.PainelFuncionarios;
import cadastros.PainelProdutos;
import controller.BairroController;
import controller.ClienteController;
import controller.FuncionarioController;
import controller.ProdutoController;
import dto.BairroDTO;
import dto.ClienteDTO;
import dto.FuncionarioDTO;
import dto.ProdutoDTO;

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBCliente = new javax.swing.JButton();
        jBFuncionario = new javax.swing.JButton();
        jBProduto = new javax.swing.JButton();
        jBBairro = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMClientes = new javax.swing.JMenuItem();
        jMFuncionarios = new javax.swing.JMenuItem();
        jMProdutos = new javax.swing.JMenuItem();
        jMBairros = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Clientes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setMinimumSize(new java.awt.Dimension(534, 104));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jBCliente.setText("Cliente");
        jBCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBClienteActionPerformed(evt);
            }
        });
        jPanel1.add(jBCliente);

        jBFuncionario.setText("Funcionario");
        jBFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(jBFuncionario);

        jBProduto.setText("Produto");
        jBProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(jBProduto);

        jBBairro.setText("Bairros");
        jBBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBairroActionPerformed(evt);
            }
        });
        jPanel1.add(jBBairro);

        jButton5.setText("Sair");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Cadastros");

        jMClientes.setText("Clientes");
        jMClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMClientesActionPerformed(evt);
            }
        });
        jMenu1.add(jMClientes);

        jMFuncionarios.setText("Funcionarios");
        jMFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMFuncionariosActionPerformed(evt);
            }
        });
        jMenu1.add(jMFuncionarios);

        jMProdutos.setText("Produtos");
        jMProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(jMProdutos);

        jMBairros.setText("Bairros");
        jMBairros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMBairrosActionPerformed(evt);
            }
        });
        jMenu1.add(jMBairros);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Listagem");

        Clientes.setText("Clientes");
        Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesActionPerformed(evt);
            }
        });
        jMenu2.add(Clientes);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBairroActionPerformed
        // TODO add your handling code here:
        new Listagem(this, true, new BairroController(),new PainelBairros(new BairroDTO())).setVisible(true);
    }//GEN-LAST:event_jBBairroActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jBClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBClienteActionPerformed
        // TODO add your handling code here:
        new Listagem(this, true, 
                new ClienteController(),
                new PainelClientes(new ClienteDTO())
        ).setVisible(true);
        
    }//GEN-LAST:event_jBClienteActionPerformed

    private void jMClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMClientesActionPerformed
        // TODO add your handling code here:
        new CadastroPadrao(this, true, 
                new PainelClientes(new ClienteDTO()),
                new ClienteController()).
                setVisible(true);
    }//GEN-LAST:event_jMClientesActionPerformed

    private void jBProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBProdutoActionPerformed
        // TODO add your handling code here:
        new Listagem(this, true, new ProdutoController(),new PainelProdutos(new ProdutoDTO())).setVisible(true);
    }//GEN-LAST:event_jBProdutoActionPerformed

    private void jBFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFuncionarioActionPerformed
        // TODO add your handling code here:
        new Listagem(this, true, new FuncionarioController(), new PainelFuncionarios(new FuncionarioDTO())).setVisible(true);
    }//GEN-LAST:event_jBFuncionarioActionPerformed

    private void jMFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMFuncionariosActionPerformed
        // TODO add your handling code here:
        new CadastroPadrao(this, true, new PainelFuncionarios(new FuncionarioDTO()), new FuncionarioController()).setVisible(true);
    }//GEN-LAST:event_jMFuncionariosActionPerformed

    private void ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesActionPerformed
        // TODO add your handling code here:
        new Listagem(this, true, new ClienteController(), new PainelClientes(new ClienteDTO())).setVisible(true);
    }//GEN-LAST:event_ClientesActionPerformed

    private void jMBairrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMBairrosActionPerformed
        new CadastroPadrao(this, true, new PainelBairros(new BairroDTO()), new BairroController()).setVisible(true);
    }//GEN-LAST:event_jMBairrosActionPerformed

    private void jMProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMProdutosActionPerformed
        new CadastroPadrao(this, true, new PainelProdutos(new ProdutoDTO()), new ProdutoController()).setVisible(true);
    }//GEN-LAST:event_jMProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Clientes;
    private javax.swing.JButton jBBairro;
    private javax.swing.JButton jBCliente;
    private javax.swing.JButton jBFuncionario;
    private javax.swing.JButton jBProduto;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMBairros;
    private javax.swing.JMenuItem jMClientes;
    private javax.swing.JMenuItem jMFuncionarios;
    private javax.swing.JMenuItem jMProdutos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
