/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package cadastros;

import interfaces.InterfaceController;
import interfaces.InterfaceDTO;
import interfaces.InterfacePainel;
import java.awt.BorderLayout;
import util.Util;

/**
 *
 * @author Sayuri
 */
public class CadastroPadrao extends javax.swing.JDialog {

    private final InterfacePainel painel;

    private final InterfaceController controller;
    
    public CadastroPadrao(java.awt.Frame parent, boolean modal,
            InterfacePainel painel, InterfaceController controller) {
        super(parent, modal);
        initComponents();
        this.painel = painel;
        this.controller = controller;
        add(this.painel,BorderLayout.CENTER);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbCancelar = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbCancelar.setText("Cancelar");
        jbCancelar.setMaximumSize(new java.awt.Dimension(100, 100));
        jbCancelar.setMinimumSize(new java.awt.Dimension(100, 40));
        jbCancelar.setPreferredSize(new java.awt.Dimension(100, 40));
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jbCancelar);

        jbSalvar.setText("Salvar");
        jbSalvar.setMaximumSize(new java.awt.Dimension(100, 100));
        jbSalvar.setMinimumSize(new java.awt.Dimension(100, 40));
        jbSalvar.setPreferredSize(new java.awt.Dimension(100, 40));
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(jbSalvar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        InterfaceDTO dados = painel.getDados();
        controller.setDto(dados);
        Integer id = Integer.valueOf(Util.numeroValido(dados.id));
        if(id>0){
            if(controller.editar())
                dispose();
        }else{
            if(controller.salvar())
                dispose();
        }
    }//GEN-LAST:event_jbSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbSalvar;
    // End of variables declaration//GEN-END:variables
}
